### PR TITLE
Renew of the documentation

### PR DESCRIPTION
**Pull request by Kovah**
I had some difficulties with getting started and had to search re-read large parts of the documentation to understand how some things are working.
That's why I sat down and thought about how to improve the documentation and here are the changes:

* Restructures the docs into more categories, splits 'making games' into multiple documents
* Use Grunt to compile all assets and moves them into new directory
* Styles are now handled by Sass
* Update to Bootstrap 4
* Replace Prettify.js with highlight.js
* Updates the base templates

**Previews**
* [Frontpage](https://cloud.githubusercontent.com/assets/1816101/20349892/b503600a-ac0c-11e6-946d-f0b00c3fd1db.png)
* [Making Games page](https://cloud.githubusercontent.com/assets/1816101/20349933/e684b656-ac0c-11e6-9051-bf71426ee2ca.png)

**Precompiled assets**
At the moment some of the assets like `styles.css` and JS dependencies are removed from version control. If it's necessary to have them available in the repo, we can commit them again.

---

I really hope that all changes are fine. If not, just leave a comment and I will correct. 😃

### CODE REVIEW

**Comment by greggman** [comment]
It's amazing that you're putting so much work into this. Is there any way you and break this into multiple PRs? There's too much to look at here.

Examples:

* a pr to move the assets
* a pr to use scss
* a pr to update .md files
* a pr to replace prettify.js with highlight.js

etc... 

Also a few things

1. I don't build the docs. In other words if you're updating `.md` files please only update those. Don't update the corresponding html files.

2. Please stick to the style as is. Do not remove blank lines, don't add or remove spaces, don't go changing coding styles please. Thanks.

**Comment by Kovah** [comment]
Yeah I really like this project, it's astonishing how well the system works and I know how important help is.
I will try to split this up into multiple PRs tomorrow.

If HTML files should not be updates would it make sense to completely remove them from the repository?
Also, do you have an example where the code style was changed? Can't remember all changes..

**Comment by greggman** [comment]
It's hard to read the diffs and I didn't go searching for all places but for example in `changelist.md` the diff appears to show all blank lines removed and a few other files. In `writing-games.md` moved from `makinggames.md` the `controller.js` section has been refomatted similarly in other places. In `Gruntfile.js` spaces have been added after `function`. Names have been changed to have `under_scores` etc...

**Comment by Kovah** [comment]
Ok I will look into this.

**Comment by Kovah** [comment]
What about the HTML files? Should they be removed from the repo if they should not be commited anyway?

**Pull request closed without merging**
